---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chargehq-occp-proxy
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    image:
      repository: nginx
      tag: alpine3.18-slim
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ocpp.${BASE_DOMAIN}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 33033             # http://ocpp.dev.en-plus.cn:33033
            targetPort: 80
    configmap:
      config:
        enabled: true
        data:
          nginx.conf: |
            http {
                server {
                    listen 80;
                    location / {
                        proxy_pass https://ocpp.chargehq.net/;
                        proxy_ssl_server_name on;
                    }
                }
            }

            events {
            #   worker_connections  4096;  ## Default: 1024
            }
    persistence:
      config:
        enabled: true
        type: configMap
        name: "{{ .Release.Name }}-config"
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
