---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chargehq-occp-proxy
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    image:
      repository: nginx
      tag: alpine3.18-slim
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ocpp.${BASE_DOMAIN}
        externalTrafficPolicy: Local
    ports:
      http:
        port: 33033
        # https://ocpp.dev.en-plus.cn:33033
    configmap:
      config:
        enabled: true
        data:
          nginx.crt: |
            -----BEGIN CERTIFICATE-----
            MIIDazCCAlOgAwIBAgIUN2IL5JvwB+Qd88uSvtcCnEDAqoIwDQYJKoZIhvcNAQEL
            BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
            GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzExMjMwNDAxMjhaFw0yNDEx
            MjIwNDAxMjhaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
            HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
            AQUAA4IBDwAwggEKAoIBAQCrjjBQO3zLxIKJUSD3rgJs9qZpdbvggVcPUYEbK+uY
            rJHY00YbsjSjQwu6iaXHNodw54WGOgXjfdsXWaNQmyFK6vn5asyjqO8WjQqTDfoL
            ymMHrCEcZs1/D3Ia2NL+x4Keg+fE9IOokSD7M4AAK27wVTqnfJ9irReAlHekaxsz
            eL9T/J3DKVm+1f2xlWmx5FS71SbJQa+Cj58w7IBVP40GmVYjv7w78ZTZKvBRP58a
            2BU05W45E3GTJ8tQbqaI2vjvQeCrU3Q6B4ehbwOrdGSE0RuCgofaF9u71oTo8qFz
            5sMgyXlHcd4bJl9FNwYVXc9hZo7TBwmvxCV7kkTx4ktVAgMBAAGjUzBRMB0GA1Ud
            DgQWBBQLhPPEbICwMFfJX7NlcPIvcnX8vDAfBgNVHSMEGDAWgBQLhPPEbICwMFfJ
            X7NlcPIvcnX8vDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCA
            Kqz/cbyipQ9dhkBAc4PEqarpMWWmbmp2hSEjcP32PXans+9q0bdy8fLa7AMOcFTE
            7bavNUA3fKXlDdTLKZrEsKXCf3aqBRFnMlj7+dBjIWEJpcva1MP/jtE3xkk9WrMw
            dlXPd+ePmo8TmDdjOgaKqUJNgBD4fbrdH4G48g5xPLmwiRvfQp/5ES9Ny1ZGNsuj
            i9wlew45Oozq9k2LNwZjM7c8ATj5aG1zpxcDpc5YD7d3wpaYVZqcebqv7uXT+yfz
            8MbtBaJ2u8xCM+NYItyXg5UcrLOSu/Ou6DvggIX23eDwg2vNy5JJT6NktXfFr62o
            KZE46c819kFavgHxfbHD
            -----END CERTIFICATE-----
          nginx.key: |
            -----BEGIN PRIVATE KEY-----
            MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrjjBQO3zLxIKJ
            USD3rgJs9qZpdbvggVcPUYEbK+uYrJHY00YbsjSjQwu6iaXHNodw54WGOgXjfdsX
            WaNQmyFK6vn5asyjqO8WjQqTDfoLymMHrCEcZs1/D3Ia2NL+x4Keg+fE9IOokSD7
            M4AAK27wVTqnfJ9irReAlHekaxszeL9T/J3DKVm+1f2xlWmx5FS71SbJQa+Cj58w
            7IBVP40GmVYjv7w78ZTZKvBRP58a2BU05W45E3GTJ8tQbqaI2vjvQeCrU3Q6B4eh
            bwOrdGSE0RuCgofaF9u71oTo8qFz5sMgyXlHcd4bJl9FNwYVXc9hZo7TBwmvxCV7
            kkTx4ktVAgMBAAECggEAGlKkI59pD9v8WoT9/brvqNf0o0BbHkDCQrmzCWAFE4VB
            EKekPXorvPQ737ignO9HO2Hu2TBceHI2dH/+wM64vkXNKsHCGgeA/fEQsw0lNXtt
            k/8Lio/Ujp8oVym3QDwNFPTw0kXhULNJ//lANeZ0LICrUgkbbJjZ/xLow6vifdRT
            sugT2i8Eg93QyofSmULpRkzh2pXC9neY+qyUBf/eD/lHNDffTVpKy7l9Wa5uZ5Ko
            kWNpuLH2nqxiy8Oofw2vrXEgQrUqXNha0uwxsQ2NFBnwwh0zNlkI/UBBnh8b36yh
            Vs9uKKR0hcfaYkBZk9zEECX07G9y6CdJocRcgiUe8QKBgQDqS1z8D88v3VeHHcUC
            OgrswWsNF29mlSIUyDfcBOz0aNayC+S6aIYkwIZsPVJygXq6T6eR9WF6+UPsk6Ze
            fh1KcrFPFaSSR4C7BsSs4KkoC27xyKVhWK37gyRKlh5sQjud4aJt+6wNn07J8nno
            +cjNganaPTBsX1o8pmyQn8qjEQKBgQC7cuDmSMtdPTRjkGs8o6FpBD5fSPtuJc9D
            SPObe/RFvdXOb7jax7nEwbPSGJqEGs+dGRZlyUM5suIopq+X2p7b1JwvZavM5k65
            OTfBdiih1oPUGK768g8qom4Xt2bSKUlPThBoBM/SUs6Pgn37ZvenIyFoywLBpyT3
            2FlLZSNcBQKBgQDSBhSob5OOmJ/poyoDQPyiFxBbf/KAxpbygjhwpomy3nf2yuqS
            nzgAogTd6mqJ8r+NW/IeyRRFJEVbQVAVzH99SSrgdco8xpQDE6IiRpHcL8OYQgDe
            LpxnpbtWkRNcgFLoyGbOqJgm7fO23AGkcqUqc11LISbTPvao/5a6XkNLwQKBgGlR
            dFcu00RB3SuLuxTJAymT/s9enBYZHEi7tlPH40lEDdr9HqmdyhxokPYcaMSMo9Wq
            gNETsbe7cCJS9Rmm9dahsFdZEpv/Un/zTAZgsxerBUqny7inRCo6NQ0SOK0gEVaD
            j+hBu9p6OCCdutcD1WWM8XqFhbj0hmrSnekknCdZAoGARlYXl2O00Dkn7gtUIEBL
            7jEnV+lFo9PlqPPRP6J2ccMXFIq7xcVwFL2HSdaXXLUf8E6xVzfDLfkJMadL9oJ1
            E9zJcVJk8vsaFpKfqbchn2+BhoISVtvqmCuCKuoDoGBes6LQawIZlzPszWACCtOo
            78pdFPMCwkqtM3E5g6ukZwk=
            -----END PRIVATE KEY-----
          nginx.conf: |
            http {
                ssl_certificate /etc/nginx/nginx.crt;
                ssl_certificate_key /etc/nginx/nginx.key;
                server {
                    listen 33033;
                    location / {
                        proxy_pass https://ocpp.chargehq.net/;
                        proxy_ssl_server_name on;
                    }
                }
            }

            events {
            #   worker_connections  4096;  ## Default: 1024
            }
    persistence:
      config:
        enabled: true
        type: configMap
        name: "{{ .Release.Name }}-config"
        mountPath: /etc/nginx
        # subPath: nginx.conf
