apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  frigate-media
  namespace: default
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
