# HelmRelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: flux-system
  labels: {}
spec:
  interval: 5m
  targetNamespace: vpn-networking
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.x.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    routed_namespaces:
    - vpn
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.43.0.0/16 # pod network is there, just not services
