---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-system
spec:
  interval: 5m
  releaseName: k10
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io
      chart: k10
      version: 4.0.13
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    # eula:
    #   accept: true
    #   company: 
    #   email: 

    clusterName: k8s

    # auth:
    #   tokenAuth:
    #     enabled: true

    ingress:
      create: true
      host: k10.${BASE_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
      urlPath: k10
      hosts:
        - k10.${BASE_DOMAIN}
      tls:
        enabled: true
        secretName: tls.k10

    # prometheus:
    #   enabled: true
    #   server:
    #     persistentVolume:
    #       enabled: false

  # postRenderers:
  #   - kustomize:
  #       patchesJson6902:
  #         - target:
  #             kind: Ingress
  #             name: k10-ingress
  #           patch:
  #             - op: add
  #               path: /spec/ingressClassName
  #               value: traefik
