---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: dns-etcd
  chart:
    spec:      
      # renovate: registryUrl=https://stevehipwell.github.io/helm-charts/
      chart: external-dns
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
  install: {}
  interval: 10m0s
  targetNamespace: kube-system
  values:
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://dns-etcd-client:2379
