---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  chart:
    spec:
      chart: home-assistant
      version: 10.x.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  install: {}
  interval: 1m0s
  values:
    env:
      TZ: Australia/Sydney
    # persistence:
    #   config:
    #     enabled: true
    #     mountPath: /config   
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        # tls:
        #   - hosts: [ homeassistant.192.168.58.135.sslip.io ]
        #     secretName: homeassistant-tls
        hosts:
          - host: homeassistant.192.168.58.135.sslip.io
            paths:
              - path: /
          - host: homeassistant.192.168.58.174.sslip.io
            path:
              - path: /