# HelmRelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
  labels: {}
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    nodeSelector:
      storage: longhorn
      kubernetes.io/hostname: pve
    image:
      repository: jacobalberty/unifi
      tag: v9.1.120
    env:
      TZ: Australia/Sydney
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          traefik.ingress.kubernetes.io/service.serversscheme: https
        tls:
          - hosts:
            - unifi.${BASE_DOMAIN}
            secretName: unifi-tls
        hosts:
          - host: unifi.${BASE_DOMAIN}
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 2Gi
        accessMode: ReadWriteOnce
        # NEED right type size etc...
    service:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: controller-unifi.${BASE_DOMAIN}
        type: LoadBalancer
        externalTrafficPolicy: Local
