---
# Redirect to https
apiVersion: traefik.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirectscheme
  namespace: network-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
