---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: code-server
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: flux-system
      version: 1.x.x
  install: {}
  interval: 10m0s
  targetNamespace: default
  values:
    secret: {}
    env:
      TZ: Australia/Sydney
    ingress:
      enabled: true
      tls:
        - hosts:
          - code.${BASE_DOMAIN}
          secretName: code-server-tls
      hosts:
        - host: code.${BASE_DOMAIN}
          paths:
            - pathType: Prefix
              path: /
    persistence:
      config:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: code-server-install-secrets
      valuesKey: password
      targetPath: secret.PASSWORD
    - kind: Secret
      name: code-server-install-secrets
      valuesKey: password
      targetPath: secret.SUDO_PASSWORD
    