apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:pc3sk7lETDc=,iv:EaY2yHsy91HJDUVTpIDS8iC40cV05bnYjHxgsGtg2pA=,tag:9A1KOSbJK+HN4/Im3jiuvA==,type:str]
kind: Secret
metadata:
    name: code-server-install-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-11T04:34:38Z"
    mac: ENC[AES256_GCM,data:HmYQxCm1zuzW6a/U3dUiKeTKKu2l+lzujwUWIDmCpVmg0jYC0DG4ayZ+z1hcNcBp44dYKb5nIWHrsRADXALEx+VS5C9aQwuvK5PWNKXk6y7O565PgV/QeVWayEUqzZlC53LrysXiKfLBWCes0ZDcVGTT570C9TiO25P5CteePHY=,iv:RoU9IPmMhpVxufVwT9l/Gq+Wty0a26tlVBrFtYR/qSQ=,tag:IeXDzkA+frDKiY0sESoepg==,type:str]
    pgp:
        - created_at: "2021-08-31T21:09:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/M6fje6Wa1jAQ/9H06bWq7HgwsqR+4+l+jzsYtbsEcGUswlhVeuTXLHH93A
            nPqMFQ27R0b2Q5Eoa/AjC+kfu6OCzEEW/94Kc/fBjYn3NF6WguSgzyF+UHMeDpyx
            w1eTL9Yf9a9dc7YbFsA+PSXBIcoVbP9g50kEhK9DtkcHNgI89QawOtD4VhJShtYO
            MljI0/sjNPWJUyh9UFEk43BXxWctjhLkUANeOOLc9TveGisQFOn6Ryk+2QepfoEH
            WiwIapqu4mWWMhs0FoXtYH0r710WL6obnkSRcv7CVXodj5AihuiWeGmIT+XdRwXx
            QETJZggggBPqMsbIHFVM9d7xx/FsQxsCiDeELR2ol/d21GkpRN74t8fxSxCRKwzc
            K55sbSo/cb3yXknWVcPVZdtyawifPf0f1/KvVmK/tr37VYQFZsprkI/FuKJePKUf
            klX32BCjUTT1X4RtFey8mouc4kzLQtZynXdF5y0kSwn33doNzQJYhbwvkfpNxbCc
            zVNMYpl2CXjTmAc3MfrQIJOB10/qGEK2wGRQGzGsxwxH4Bf69zMc1whhKAMn0Ft+
            9lEabInmtOe9v0gqZt+UjIbKaX0pdayngHVLdFEzw8kSkhBrg1kUPahgAvm5IjZA
            haFHTatnsWv125+fM+DjYTL4iR48spCT1StdqrwzARgYBCRXdYcVKulgO4TbrMTU
            aAEHAhVxp5MpN+5SYMgVNu55IVmG+qWu9wQpOeqpOWzXxubLyUsHHkfR+CpvKKPD
            NRBkCwrO6gDHIwrSavLjwjKBwLfm5UnW4E6b8YJhhyJPIOuz3N+Yjb87qtEfEr6u
            7sE65MmyNgQd
            =SB6k
            -----END PGP MESSAGE-----
          fp: E1B9ED7DD949E306B657E2EB001154C49571BA66
        - created_at: "2021-08-31T21:09:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/wevS2MWPqcAQ//ST0HFOedJ+ipEE93K+ptlfoHMdND11fOKNNrfoxbx7us
            zmoWizSTw3tJbqOlYjFOX+o8s8BDMiLqG4mDhKt6rk1bZmZUzMWFUf1Bq7HyonF2
            upgl9pBkmYbb/gbRQHZ9Ji9bJcxCcpKf6MtxYmafd7n6VtCfOG1muw/UzHNN/jlh
            strCvPi++C0Q3xaQvJjSKvvDHxkUI+dcM2iZdMV1aCJ5hGV5dQAi9vmIbdIEJMS2
            9QQP/jiDF9X1GWKdez4xxdt6n/OAn25NnjVi6S2D5mKiwU1TFeYEX0kHhK6vkkIZ
            OMz5iRi4TdkAjFRnCm4UAX+hT5ihaRXhP9Sws/uG2kuBTkarpRMrASs6v6LsJrbN
            qAzIcrpeqX+bsMH7vwBk3q7ZJ1bLIndJMH64ZEqi7QG1buw6y2KJizJ8xmOozVwB
            ru1rE6S6K1ANNoOPRF8iUF05Sz+fjH83vQOIf3osJW7tK11OB3zFCqkDAIrfgpNH
            3tqd1Ce+nPGAVYiaZK7czJgiZMOv59D/HZPiEmNMjXUFqAIJ0sExlNRBR7/Czxbu
            k7MGkD08nvafGEGWeY3Nyh4F2ceZjA7/3PbJkO/kelBOsN2kkKersA/tHCETEy0B
            XV01J5gYYSlD+6TbuRyfOEkDYMJZd5k/Y7rZFkMhBnGAxbdlSNz3za2oMUbhD9XU
            aAEHAhVYA+rgquPu+kuIgFdLqT/073kJSowWlU8PV3Uaf8zvOfoUeqH5gl16HbhU
            6NKmZtGSQ5GQEOrEUlWu8HnVIzXo/zqmVkAa3wndqNTYThUeih2n9qww2k13hmla
            D0eS/LapzQ4e
            =XK8i
            -----END PGP MESSAGE-----
          fp: DC28FBF0B880CCFC8CC1F5144447FB4C8CBA9DE0
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
