---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: jellyfin/jellyfin
      tag: 10.7.7
      pullPolicy: IfNotPresent

    env:
      TZ: "Australia/Sydney"
    nodeSelector:
      feature.node.kubernetes.io/custom-intel-gpu: 'true'

    persistence:
      config:
        enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        hosts:
          - host: jellyfin.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls.jellyfin
            hosts:
              - jellyfin.${BASE_DOMAIN}

    resources: {}
      