---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: raspbernetes/velero-csi-plugin:v0.2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    metrics:
      enabled: false
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: ${VELERO_BACKUP_BUCKET}
        default: false
        config:
          region: ${AWS_REGION}
      volumeSnapshotLocation:
        provider: csi
    deployRestic: true
    credentials:
      useSecret: true
      existingSecret: ${VELERO_SECRET_NAME}
    restic:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
    kubectl:
      image:
        repository: appscode/kubectl
        tag: "1.20"
    schedules:
      daily:
        disabled: true
    #     # labels:
    #     #   myenv: foo
    #     # annotations:
    #     #   myenv: foo
    #     schedule: "0 17 * * *" # approx 3am
    #     useOwnerReferencesInBackup: true
    #     template:          
    #       ttl: "720h"
    #       # includedNamespaces:
    #       # - '*'
    #       includedResources:
    #         - pod
    #         - persistentvolumes
    #         # - persistentvolumeclaims
    #       snapshotVolumes: false
    #       defaultVolumesToRestic: false
