---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.23.11
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    metrics:
      enabled: false
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: ${VELERO_BACKUP_BUCKET}
        default: true
        config:
          region: ${AWS_REGION}
    deployRestic: true
    credentials:
      useSecret: true
      existingSecret: ${VELERO_SECRET_NAME}
    restic:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
