# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helrelease.yaml
  - freenas-secret.sops.yaml
  - backup-location-freenas.yaml
  - backup-location-backblaze.yaml
  - schedule-minio.yaml
  - schedule-backblaze.yaml
