---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.27.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    strategyType: Recreate
    podAnnotations:
      backup.velero.io/backup-volumes: config
    nodeSelector:
      storage: longhorn
    image:
      repository: ghcr.io/pi-hole/pihole
      tag: "2025.04.0"
    # maxUnavailable: 25%
    # maxSurge: 25%
    antiaff:
      enabled: true
      avoidRelease: pihole
    podDnsConfig:
      enabled: false
    serviceDhcp:
      enabled: false
    persistentVolumeClaim:
      enabled: true
      # accessModes:
      #   - ReadWriteOnce
      storageClass: longhorn
    # dnsmasq:
    #   upstreamServers:
    #     - 
    serviceWeb:
      # loadBalancerIP: 192.168.178.252
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: pihole-svc
      type: ClusterIP
    virtualHost: pihole.${BASE_DOMAIN}
    serviceDns:
      # loadBalancerIP: 192.168.178.252
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    DNS1: false
    DNS2: false
    # probes:
    #   liveness:
    #     timeoutSeconds: 10
    #   readiness:
    #     timeoutSeconds: 10
    extraEnvVarsSecret:
      FTLCONF_webserver_api_password:
        key: password
        name: pihole-password
    extraEnvVars:
      TZ: Australia/Sydney
      FTLCONF_dns_upstreams: '192.168.100.1'
      FTLCONF_webserver_port: '80,[::]:80'
      FTLCONF_dns_interface: eth0
      FTLCONF_dns_listeningMode: ALL
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
        traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        hajimari.io/appName: PiHole
        hajimari.io/enable: "true"
        hajimari.io/icon: home-automation        
      tls:
        - hosts:
          - pihole.${BASE_DOMAIN}
          secretName: pihole-tls
      hosts:
        - pihole.${BASE_DOMAIN}
  postRenderers:
    - kustomize:
        patchesJson6902:
        - target:
            group: apps
            version: v1
            kind: Deployment
            name: pihole
          patch:
            - op: replace
              path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
              value: /admin/login
            - op: replace
              path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
              value: /admin/login
