---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.34.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    strategyType: Recreate
    podAnnotations:
      backup.velero.io/backup-volumes: config
    nodeSelector:
      storage: longhorn
    image:
      repository: ghcr.io/pi-hole/pihole
      tag: "2025.08.0"
    # maxUnavailable: 25%
    # maxSurge: 25%
    antiaff:
      enabled: true
      avoidRelease: pihole
    podDnsConfig:
      enabled: false
    serviceDhcp:
      enabled: false
    persistentVolumeClaim:
      enabled: true
      # accessModes:
      #   - ReadWriteOnce
      storageClass: longhorn
    # dnsmasq:
    #   upstreamServers:
    #     - 
    serviceWeb:
      # loadBalancerIP: 192.168.178.252
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: pihole-svc
      type: ClusterIP
    virtualHost: pihole.${BASE_DOMAIN}
    serviceDns:
      # loadBalancerIP: 192.168.178.252
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    DNS1: '192.168.100.1'
    DNS2: false
    # probes:
    #   liveness:
    #     timeoutSeconds: 10
    #   readiness:
    #     timeoutSeconds: 10
    extraEnvVars:
      TZ: Australia/Sydney
      FTLCONF_dns_interface: eth0
      FTLCONF_dns_listeningMode: ALL
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
        traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        hajimari.io/appName: PiHole
        hajimari.io/enable: "true"
        hajimari.io/icon: home-automation        
      tls:
        - hosts:
          - pihole.${BASE_DOMAIN}
          secretName: pihole-tls
      hosts:
        - pihole.${BASE_DOMAIN}
