apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: pihole
spec:
  persistentVolumeClaim:
    claimName: pihole
  schedule:
    - every: "10 minutes"
      keep: 3
  template:
    spec:
      volumeSnapshotClassName: freenas-nfs-csi
