---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-home-static
  namespace: apps-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "macvlan-home-static",
      "type": "macvlan",
      "master": "eth0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "static"
      }
    }
