---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    timeout: 10m
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2025.8.1
    env:
      TZ: Australia/Sydney
    nodeSelector:
      storage: longhorn
    probes:
      startup:
        # custom: true
        # -- The spec field contains the values for the default readinessProbe.
        # If you selected `custom: true`, this field holds the definition of the readinessProbe.
        # @default -- See below
        spec:
          # initialDelaySeconds: 0
          # timeoutSeconds: 1
          ## This means it has a maximum of 10*60=600 seconds to start up before it fails
          periodSeconds: 20
          failureThreshold: 60
    podAnnotations:
      backup.velero.io/backup-volumes: config2
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"macvlan-home-static",
          "namespace": "network-system",
          "ips": ["${HOMEASSISTANT_IP}/24"]
        }]
    persistence:
      config2:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 8Gi
      config:
        enabled: false
        mountPath: /config-old
        readOnly: false
        # existingClaim: default-homeassistant-home-assistant-config
      nginx-config:
        enabled: true
        type: configMap
        name: home-assistant-nginx-config
        mountPath: "-"
        readOnly: true
        subPath: nginx.conf
    # service:
    #   hap:
    #     enabled: true
    #     annotations:
    #       external-dns.alpha.kubernetes.io/hostname: homekithap.${BASE_DOMAIN}
    #     type: LoadBalancer
    #     ports:
    #       hap:
    #         enabled: true
    #         port: 21064
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Home Assistant'
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          # hajimari.io/url
        tls:
          - hosts:
            - homeassistant.${BASE_DOMAIN}
            - ha.${BASE_DOMAIN}
            secretName: homeassistant-tls
        hosts:
          - host: homeassistant.${BASE_DOMAIN}
            paths:
              - path: /
          - host: ha.${BASE_DOMAIN}
            paths:
              - path: /
    additionalContainers:
      nginx:
        image: "nginx:1.29.0-alpine"
        imagePullPolicy: IfNotPresent
        ports:
          - name: nginx
            containerPort: 80
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
            readOnly: true
          - name: config2
            mountPath: /share/nginx
            subPath: tesla
            readOnly: true
    configmap:
      nginx-config:
        enabled: true
        data:
          nginx.conf: |
            server {
                listen 80;
                listen [::]:80;
                server_name tesla.home; # Change to match your own FQDN
                root /share/nginx;
                # static public key for Tesla
                location /.well-known/appspecific/ {
                    try_files /com.tesla.3p.public-key.pem =404;
                }
            }
    addons:
      netshoot:
        enabled: false
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.102.2
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
            traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          tls:
            - hosts:
              - config.homeassistant.${BASE_DOMAIN}
              secretName: homeassistant-code-server-tls
          hosts:
            - host: config.homeassistant.${BASE_DOMAIN}
              paths:
                - path: /
        volumeMounts:
          - name: config2
            mountPath: /config
