---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    timeout: 10m
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.3.8
    env:
      TZ: Australia/Sydney
    podAnnotations:
      backup.velero.io/backup-volumes: config
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"macvlan-home-static",
          "namespace": "network-system",
          "ips": ["${HOMEASSISTANT_IP}/24"]
        }]
    persistence:
      config:
        enabled: true
        mountPath: /config
        # existingClaim: default-homeassistant-home-assistant-config
    # service:
    #   hap:
    #     enabled: true
    #     annotations:
    #       external-dns.alpha.kubernetes.io/hostname: homekithap.${BASE_DOMAIN}
    #     type: LoadBalancer
    #     ports:
    #       hap:
    #         enabled: true
    #         port: 21064
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Home Assistant'
          # hajimari.io/url
        tls:
          - hosts:
            - homeassistant.${BASE_DOMAIN}
            - ha.${BASE_DOMAIN}
            secretName: homeassistant-tls
        hosts:
          - host: homeassistant.${BASE_DOMAIN}
            paths:
              - path: /
          - host: ha.${BASE_DOMAIN}
            paths:
              - path: /
    addons:
      netshoot:
        enabled: true
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.2.0
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          tls:
            - hosts:
              - config.homeassistant.${BASE_DOMAIN}
              secretName: homeassistant-code-server-tls
          hosts:
            - host: config.homeassistant.${BASE_DOMAIN}
              paths:
                - path: /
        volumeMounts:
          - name: config
            mountPath: /config
