apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgChdEOIO9EaGMR50+JOu+axyYPGICaoKJWULovaCPUwG/j7Z/3FPXAxYvsXxigwrT13VJDHFvpyMztt0UE4NFB6nXD1hUKgzDkKhBLFr+2TFaitp7BwC5Q/xdQ8Zce5ZGYpwJdXwBZ3EnTrbubje3YhhBERIm6Q/yS/qGNejue67pP9FswtnYxNquPdVS9MzqltxpfHoBZU88lMFUP/KD3llIbcVTh9WM4GLKT8YS7hv+CZwjbZQiUkiYzDzACeCg4CIEI5REmrStTZcWBjih1ludlrRnz1+L2sb0vpb0OazMlMa38yKfsZzuw5Noi/bSQWdrahgm2DtAgOYmmff4TyOTm4oXioqsXc1Z4/sOy53qRx2032xI3AK5Ut1JNruYAVPkgkFfOUywV1szSfEl+TUl4c9Kng3az9EDA3WvOtjrddYNeB8tpz8kIzXdmSfe19MLzBXLj9QzEPPh1LnQbwhxH6jgSlJ2zyqGkDhaS0d9r4Q1BBD27D7GukDEXXxyYyqGoW0aOJfdKIaYl3DC+BdqFDhgZYQsnQn7hF/0Q+9Bfbci72yA6ocCK0iMwF7k8ZI2zBtnWxT5VVirRMirjz5sTd1cOBjmkLJj4gqvcdWWxkuyv26avLRsDsqSWBEJgExak0x108s7NZ5uyypgSrGfaYwECYGdF4qSKyoRtInxtAgUnz06Ht0SnSaYLrY2KNkeKMe6IQVjy5RJnTdYER1+cBCJBNUJJyMFT7vlXq0ZQCSZhp5eXt+pok8a1ENJow71y9G2e/Sx+J77hHpwtsqZ4L+IHrjAolfUVQk/EUR60=
  template:
    data: null
    metadata:
      name: slack-url
      namespace: flux-system

