---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mailu
  namespace: flux-system
spec:
  interval: 2h
  url: https://mailu.github.io/helm-charts/
  timeout: 3m
  