---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nicholaswilde
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://nicholaswilde.github.io/helm-charts/

