apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: freenas-password
  namespace: flux-system
spec:
  encryptedData:
    host: AgB4EFwmNiD4fXY2Ch5iFWJSEbpjOT2V0ceitg+Svmkc/itrUoG6u0SoRTKRO2Kys9eVCMHyr1tekKIwQPaCbVG+w8ZuZT+p56v85CDNqTHnGMb0AOEjchzbiudruMl5lLmmIVKcg/4JH5Ks6k1yEkvoTpk+Lz1E+SuQ1rFelw8+WEO7PHptfCU6DsIzNnsWSOAzli68ceUfeirGvNQ+GP5FABvyjVA+CaQXf6ygTLY2RyUnYBSX411ReMpUPVI8kMpj+55AUG45zWAoeX8R/WOmSQFOcD85v5l3RtSAFgokpE0tV+9iGtruncQlwRHG/0YgKqEjZjjZLnO5VSLXLG18cD6OhIts+zKPLLQqManehsU7K9Xhuv4hNzoJYebVj6Z1iWb3dPdN94tzIP603jK5zCCoZeGVkyxja3i2sEWoPTOzSZUS8lxHXcd8Lk4RGmr7L0GlRdYm04TqNjbfLqh9+YqccFR1QsYE2NS9ebXwahaXkp6sYqB++2ClroSOOgXfsp2Y8Io3ZHh8s0hcJ8i7flmfvmsTtnegJPuzLyHKMiZZd7BGkPxPr+GQW00C8BXXx/ATzjjkuvT4Lp052JOsNo4j/PHohx1N/TNxt3ul0J7yHGqCWXcb2dzTlD35iGGpW8S180TRP1OdpdIZkqLmtebrN6p0ADXPaYijItj6BwnZn9V4kpAQE3TfSjS1eDDkB4btdFNsUXJv7n4=
    password: AgB24nPDu8nzKXxXZWCnzOcHflqXIueukIVTSo3ut+exUDAaUMwl2UeyufjdT074KngN0VAi36YDWe1060L2nfGXecUBQHwmii2VRmz3EzupanBGHRnBUaOnSPawKWhmW2H+grl4r9W5uFTaGQWypFz4C/NDPEpO6fi/Jr67PftkikWSrpDHYVv5ufSC/njfiyngiKG8VDz4doFUT3Mzj7R2n4AW03KqaFGbG1JX6YZVxy57fhgK0A2cA27ZznhBafuJGydhFh8bFvJek5E7mZXm2MhkyWR7klz7XHJOxZs4Yy2QQvvWf8ELdEP1L8nx+toAWFi7Bj9E96ijGCnrQJl9PZX/HaORueDgT8atX0aCaoTpdPZd/mpVKIsqeZw1wd/qOjuxclVndLTAP2H5bv5XlCS9PXSmug99Xjzi4qAtTOMa5lWx2DlcF13CY2or4lWre3Tu2fQ1t6NjTB7iif9z6S7AzRxvMAq6RShB+Y/81g7KhV3A+S6ZlchKBpT0pvad520WqcXPrLdk6UWlrtf8amivgeCghU9lM44mL9x3T6/j9XRGcxJgL4FvjVLJGmj7KAmDoLOEPjLzRZ/OSdX0XljNuXY/wWJehQ6n0mM4bCYBdmiB7P6zcqA7ybbZVDakPUUMQqXOKXwdp8OCf1Yfw/qPFklHHImJ0VpJb47SR2BvHHMCDl9y6X3kmyeKP3LQNs3QPogoxA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: freenas-password
      namespace: flux-system

