---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.x.x
  install: {}
  interval: 10m0s
  targetNamespace: default
  values:
    image:
      tag: 0.8.4-aarch64
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Frigate'
          # hajimari.io/url
        tls:
          - hosts:
            - frigate.${BASE_DOMAIN}
            secretName: frigate-tls
        hosts:
          - host: frigate.${BASE_DOMAIN}
            paths:
              - path: /
    env:
      TZ: Australia/Sydney
    envFrom:
      - secretRef:
          name: frigate-secrets
    persistence:
      media:
        enabled: true
        mountPath: /media/frigate
        existingClaim: frigate-media
    podAnnotations:
      # change this to force reload
      version: '4'
    config: |
      mqtt:
        host: mqtt-mosquitto
        topic_prefix: frigate
      detectors:
        cpu1:
          type: cpu
        cpu2:
          type: cpu
      #ffmpeg:
      #  hwaccel_args:
      #    - -c:v
      #    - h264_v4l2m2m
      cameras:
        fronthd:
          motion:
            mask:
              - 2013,1480,2625,1485,2619,1434,2008,1433
              - 283,936,461,958,626,658,718,926,970,892,1094,678,1092,454,903,363,741,406,663,113,296,157,197,0,0,0          ffmpeg:
          zones:
            road:
              coordinates: 837,316,1623,165,2688,163,2688,0,0,0,0,544
            front_yard
              coordinates: 2688,1520,0,1520,0,536,929,296,1619,168,2688,703
                  inputs:
              - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/1
                roles:
                  - detect
                  - rtmp
          width: 640
          width: 2688
          height: 1520
          fps: 20
        front:
          motion:
            mask:
              - 472,360,640,360,640,329,475,331
              - 139,180,162,225,227,219,243,198,265,157,258,119,218,86,151,109
              - 0,232,117,212,148,132,172,49,131,48,68,67,44,0,0,0
          zones:
            road:
              coordinates: 0,132,0,0,640,0,640,31,346,39
            front_yard:
              coordinates: 0,360,522,360,640,165,382,30,0,115              
          ffmpeg:
            inputs:
              - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/1
                roles:
                  - clips
                  - record
                  # - detect
                  # - rtmp
          width: 640
          # width: 2688
          height: 360
          # height: 1520
          fps: 15
          # fps: 20
          clips:
            enabled: true
          snapshots:
            enabled: true
      clips:
        retain:
          default: 30
          objects:
            car: 2
      snapshots:
        retain:
          default: 30
          objects:
            car: 2
      record:
        enabled: true
        retain_days: 30
      objects:
        track:
          - person
          - cat
          - car
          - bicycle
          - motorcycle
