---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: vpn
spec:
  dependsOn:
    - name: vpn-gateway
      namespace: network
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      version: 8.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: ghcr.io/linuxserver/transmission
      tag: 4.0.6-r4-ls291

    hostname: transmission

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      supplementalGroups:
        - 816
    settings:
      automaticPortSetup: false

    env:
      TZ: "Australia/Sydney"
      TRANSMISSION_WEB_HOME: /usr/share/transmission/public_html
      PUID: "921"
      PGID: "816"
      UMASK: "002"
      TRANSMISSION_DOWNLOAD_DIR: /media/downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /media/downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      DOCKER_MODS: linuxserver/mods:transmission-trguing
    persistence:
      config:
        enabled: true
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas
            path: /mnt/tank/media/downloads
        mountPath: /media/downloads
    ingress:
      main:
        enabled: true
        # ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'download'
          hajimari.io/appName: 'Transmission'
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        #   external-dns.alpha.kubernetes.io/target: ingress.${DOMAIN_1}
        #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
        #   traefik.ingress.kubernetes.io/router.middlewares: system-ingress-rfc1918-ips@kubernetescrd
        hosts:
          - host: transmission.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls.transmission
            hosts:
              - transmission.${BASE_DOMAIN}

    resources:
      requests:
        cpu: "0.3"
        memory: "1000Mi"
      limits:
        memory: "4000Mi"

    addons:
      netshoot:
        enabled: true
