---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns-external
  namespace: flux-system
spec:
  chart:
    spec:
      chart: coredns
      sourceRef:
        kind: HelmRepository
        name: coredns
      version: 1.16.x
  install: {}
  interval: 1m0s
  targetNamespace: kube-system
  values:
    isClusterService: false
    #kube-system-coredns-external-coredns
    serviceType: LoadBalancer
