---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dns-etcd
  namespace: flux-system
spec:
  chart:
    spec:      
      chart: etcd
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 6.6.x
  install: {}
  interval: 1m0s
  targetNamespace: kube-system
  values:
    image:
      repository: rancher/coreos-etcd
      tag: v3.4.16-rancher1
    persistence:
      size: 1Gi
