---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: dns-etcd
  chart:
    spec:      
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
      version: 1.1.x
  install: {}
  interval: 10m0s
  targetNamespace: kube-system
  values: # see https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://dns-etcd-client:2379
