---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-nas-media
spec:
  storageClassName: downloads-nas-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - nfsvers=3
    - local_lock=none
    - mountvers=3
    - vers=3
  nfs:
    server: 192.168.10.4
    path: /mnt/tank/media/downloads    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-downloads
  namespace: vpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: downloads-nas-downloads
  resources:
    requests:
      storage: 1Mi
