apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtl-433
  namespace: home-automation
spec:
  selector:
    matchLabels:
      app: rtl-433
  template:
    metadata:
      labels:
        app: rtl-433
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: rtl-433
          _active: true
          image: hertzg/rtl_433:alpine-3.14-20.02
          stdin: false
          stdinOnce: false
          # command:
          #   - sh
          #   - -c
          #   - sleep 1d
          args:
            - '-vv'
            - '-R'
            - '0'
            - '-X'
            - 'n=fan_kitchen,m=OOK_PWM,s=260,l=860,r=5748,g=0,t=0,y=6544,bits=25,invert,unique,get=@0:{20}:id,get=@20:{4}:code:[13:LIGHT]'
            # - '-X'
            # - n=doorbell,m=OOK_PWM,s=368,l=1088,r=5808,g=1100,t=288,y=0,bits=18,unique
            - '-X'
            # - n=fan_remote,m=OOK_PWM,s=333,l=666,r=2664,g=2551,t=150,y=0,bits=13
            - n=fan_remote,m=OOK_PWM,s=294,l=560,r=9736,g=550,t=107,y=0,bits=13
            - '-s'
            - '960000'
            - '-F'
            - mqtt://mqtt-mosquitto.home-automation.svc.cluster.local:1883,devices=rtl_433[/id]
            # - '-f'
            # - '433920000'
          tty: false
          securityContext:
            runAsRoot: true
            readOnlyRootFilesystem: false
            capabilities: {}
            privileged: true
            allowPrivilegeEscalation: true
          resources:
            limits:
             cpu: '2'
             memory: 128Mi
            requests:
             cpu: '0.1'
             memory: 20Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: feature.node.kubernetes.io/custom-rtl2832_sdr
                  operator: Exists
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
