---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts chart=node-feature-discovery
  - https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.15.4/deployment/base/nfd-crds/nfd-api-crds.yaml
