---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtorrent
  namespace: vpn
spec:
  dependsOn:
    - name: vpn-gateway
      namespace: flux-system
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: rtorrent-flood
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    image:
      # repository: ghcr.io/k8s-at-home/qbittorrent
      tag: latest
      pullPolicy: Always

    hostname: rtorrent

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      supplementalGroups:
        - 816
    settings:
      automaticPortSetup: false

    env:
      TZ: "Australia/Sydney"
    #   UMASK: "022"
    persistence:
      config:
        enabled: true
      downloads:
        enabled: true
        existingClaim: nfs-nas-downloads
        mountPath: /downloads
    #   media:
    #     enabled: true
    #     existingClaim: nfs-nas-media
    #     mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        # ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'download'
          hajimari.io/appName: 'rtorrent'
        #   external-dns.alpha.kubernetes.io/target: ingress.${DOMAIN_1}
        #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
        #   traefik.ingress.kubernetes.io/router.middlewares: system-ingress-rfc1918-ips@kubernetescrd
        hosts:
          - host: rtorrent.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls-rtorrent
            hosts:
              - rtorrent.${BASE_DOMAIN}

    resources:
      requests:
        cpu: "0.3"
        memory: "1000Mi"
      limits:
        memory: "4000Mi"

    addons:
      netshoot:
        enabled: true
