---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: util-system
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.deliveryhero.io/
      chart: node-problem-detector
      version: 2.3.14
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: registry.k8s.io/node-problem-detector/node-problem-detector
      tag: v1.35.2
    nodeSelector:
      kubernetes.io/arch: amd64
    # metrics:
    #   serviceMonitor:
    #     enabled: true
