---
# export out the k3s config from the first cluster node only
- name: make .kube dir
  file:
    path: /home/pi/.kube
    state: directory
    owner: pi
    group: pi
    mode: 0755
- name: duplciate kubeconfig
  become: true
  copy:
    remote_src: true
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/pi/.kube/config
    owner: pi
    group: pi
    mode: 0600
- name: fix up ip address in kubeconfig
  become: false
  replace:
    path: /home/pi/.kube/config
    regexp: 'https://127\.0\.0\.1'
    replace: https://{{ k3s_registration_address }}
- name: Save kubeconfig locally
  become: false
  ansible.builtin.fetch:
    flat: yes
    src: /home/pi/.kube/config
    dest: output/kubectl.conf
    fail_on_missing: yes
