---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 15.1.0
  interval: 10m0s
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.2.4.6635
    env:
      TZ: "Australia/Sydney"
    podSecurityContext:
      supplementalGroups:
        - 816
    persistence:
      config:
        enabled: true
        size: 1Gi
      media-movies:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas
            path: /mnt/tank/media/movies
        mountPath: /media/movies
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas
            path: /mnt/tank/media/downloads
        mountPath: /media/downloads
      downloads-nzb:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nas
            path: /mnt/tank/media/downloads_nzb
        mountPath: /media/downloads_nzb
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        hosts:
          - host: radarr.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls.radarr
            hosts:
              - radarr.${BASE_DOMAIN}
