---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: data
    image:
      repository: nodered/node-red
      tag: 4.1.5
    env:
      TZ: Australia/Sydney
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd          
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'node-red'
        tls:
          - hosts:
            - node-red.${BASE_DOMAIN}
            secretName: node-red-tls
        hosts:
          - host: node-red.${BASE_DOMAIN}
            paths:
              - path: /
