apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: node-red-config
  namespace: home-automation
spec:
  persistentVolumeClaim:
    claimName: node-red-config
  schedule:
    - every: "10 minutes"
      keep: 3
  template:
    spec:
      volumeSnapshotClassName: freenas-nfs-csi
