# apiVersion: v1
# kind: Service
# metadata:
#   name: receiver
#   namespace: flux-system
# spec:
#   type: NodePort
#   selector:
#     app: notification-controller
#   ports:
#     - name: http
#       port: 9292
#       protocol: TCP
#       targetPort: 9292
