apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  type: LoadBalancer
  selector:
    app: notification-controller
  loadBalancerIP: 192.168.58.250
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9292