apiVersion: apps/v1
kind: Deployment
metadata:
  name: avahi
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: avahi
  template:
    metadata:
      labels:
        app: avahi
    spec:
      hostNetwork: true
      containers:
      - name: avahi
        image: ydkn/avahi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5353
        volumeMounts:
          - mountPath: /etc/avahi
            name: config
          # - mountPath: /etc/avahi/services
          #   name: services
      volumes:
        - name: services
          configMap:
            name: avahi-services
        - name: config
          configMap:
            name: avahi-config
