# kustomization.yml
namespace: default
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: avahi-services
    files: []
      # - services/homekit.service
      # - services/home-assistant.service
  - name: avahi-config
    files:
      - avahi-daemon.conf
    