---
- name: start time services
  service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: run timedatectl status
  command: /usr/bin/timedatectl show
  changed_when: false
  check_mode: false
  register: timedatectl_result

- name: copy timesyncd config
  copy:
    content: |
      [Time]
      NTP={{ common_ntp_servers | join(' ') }}
      FallbackNTP={{ common_fallback_ntp_servers | join(' ') }}
    dest: /etc/systemd/timesyncd.conf
    mode: 0644

- name: set timezone
  command: '/usr/bin/timedatectl set-timezone {{ common_timezone }}'
  when: common_timezone not in timedatectl_result.stdout_lines[0]

- name: enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'NTP=no' in timedatectl_result.stdout"

- name: 'set hostname'
  hostname:
    name: '{{ inventory_hostname }}'


