---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 10.x.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  install: {}
  interval: 10m0s
  targetNamespace: default
  values:
    env:
      TZ: Australia/Sydney
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: default-homeassistant-home-assistant-config
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - homeassistant.home
            - ha.home
            - ha
            - homeassistant
            secretName: homeassistant-tls
        hosts:
          - host: homeassistant.home
            paths:
              - path: /
          - host: ha.home
            paths:
              - path: /
          - host: homeassistant
            paths:
              - path: /
          - host: ha
            paths:
              - path: /
