---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: network-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: multus
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.2.4
    cni:
      image:
        repository: ghcr.io/k8s-at-home/cni-plugins
        tag: v1.1.1
      version: "0.3.1"
      # paths below for normal full kubernetes - k3s uses paths which are defaulted see https://github.com/k8s-at-home/charts/tree/master/charts/stable/multus
      # paths:
      #   bin: /opt/cni/bin
      #   config: /etc/cni/net.d
    # just copying paths as the upstream chart may change this
    paths:
      # -- CNI config folder for k3s.
      # Change to `/etc/cni/net.d` for non k3s
      config: /var/lib/rancher/k3s/agent/etc/cni/net.d

      # -- CNI plugin binaries folder for k3s.
      # Change to `/opt/cni/bin` for non k3s
      bin: /var/lib/rancher/k3s/data/current/bin
