---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gemini
  namespace: storage-system
spec:
  chart:
    spec:
      chart: gemini
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      version: 0.0.7
  install: {}
  interval: 10m0s
  values:
    image:
      repository: quay.io/fairwinds/gemini
      tag: main
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: gemini-controller
          spec:
            template:
              spec:
                nodeSelector:
                  kubernetes.io/arch: amd64
