---
- hosts: all
  become: yes
  tasks:
    - debug: msg="Ansible running in {{ ansible_lsb.id }}!"
      name: hello world!
  vars:
    k3s_build_cluster: false
    k3s_become_for_all: true
  roles:
    - common
    - xanmanning.k3s
  