---
- hosts: poe_plus
  tasks:
    - name: Enable POE+
      become: true
      ansible.builtin.lineinfile:
        state: absent
        path: /boot/config.txt
        regexp: '^dtoverlay=rpi-poe-plus$'
        line: dtoverlay=rpi-poe-plus
      notify: reboot
    - name: Enable POE
      become: true
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        regexp: '^dtoverlay=rpi-poe$'
        line: dtoverlay=rpi-poe
      notify: reboot
  handlers:
    - name: reboot
      become: true
      reboot:
- hosts: all
  become: yes
  vars:
    # k3s_build_cluster: false
    k3s_become_for_all: true
    # k3s_etcd_datastore: true
    # k3s_use_unsupported_config: true
    k3s_install_hard_links: true
    k3s_server:
      kube-apiserver-arg: feature-gates=MixedProtocolLBService=true
      disable:
        - local-storage
        - servicelb
        - traefik
  roles:
    - common
    - xanmanning.k3s
- hosts: masters
  vars:
    k3s_control_node: true
  tasks:
    - name: make .kube dir
      file:
        path: /home/pi/.kube
        state: directory
        owner: pi
        group: pi
        mode: 0755
    - name: duplciate kubeconfig
      become: true
      copy:
        remote_src: true
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/pi/.kube/config
        owner: pi
        group: pi
        mode: 0600
    - name: fix up ip address in kubeconfig
      become: false
      replace:
        path: /home/pi/.kube/config
        regexp: 'https://127\.0\.0\.1'
        replace: https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
    - name: Save kubeconfig locally
      become: false
      ansible.builtin.fetch:
        flat: yes
        src: /home/pi/.kube/config
        dest: static/kubectl.conf
        fail_on_missing: yes
- hosts: workers
  vars:
    # k3s_control_node: masters
