---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: evcc-optimizer
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    controllers:
      evcc-optimizer:
        containers:
          app:
            image:
              repository: evcc/optimizer
              tag: latest
              pullPolicy: Always
            env:
              TZ: "Australia/Sydney"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /optimize/health
                    port: 7050
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /optimize/health
                    port: 7050
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
    service:
      app:
        controller: evcc-optimizer
        ports:
          http:
            port: 7050
