---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: evcc
  namespace: home-automation
# note values documented here https://artifacthub.io/packages/helm/bjw-s/common/0.2.2
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pve
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.104.2
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
            traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          tls:
            - hosts:
              - config.evcc.${BASE_DOMAIN}
              secretName: evcc-code-server-tls
          hosts:
            - host: config.evcc.${BASE_DOMAIN}
              paths:
                - path: /
        volumeMounts:
          - name: config
            mountPath: /config
    image:
      repository: ghcr.io/jeffborg/evcc
      tag: "0.300.8.0"
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    args:
      - '--config'
      - '/config/evcc.yaml'
      - '--profile'
    env:
      TZ: "Australia/Sydney"
      EVCC_DATABASE_DSN: /config/.evcc/evcc.db
      EVCC_SPONSORTOKEN: Test
      GRPC_URI: 127.0.0.1:8080
    service:
      main:
        ports:
          http:
            port: 7070
            enabled: true
            primary: false
          ocpp:
            port: 8887
            enabled: true
            primary: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        tls:
          - hosts:
            - evcc.${BASE_DOMAIN}
            secretName: evcc-tls
        hosts:
          - host: evcc.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 7070
      ocpp:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - ocpp.evcc.${BASE_DOMAIN}
            secretName: evcc-ocpp-tls
        hosts:
          - host: ocpp.evcc.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8887
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        mountPath: /config
