---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    defaultPodOptions:
      nodeSelector:
        storage: longhorn
    controllers:
      ombi:  
        containers:
          app:
            env:
              TZ: Australia/Sydney
            image:
              repository: ghcr.io/linuxserver/ombi
              tag: "4.47.1"
    service:
      app: # this can now be any name you wish
        controller: ombi
        ports:
          http:
            port: 3579
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        hosts:
          - host: ombi.${BASE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 3579
        tls:
          - secretName: tls.ombi
            hosts:
              - ombi.${BASE_DOMAIN}
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config
