---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: network-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    isClusterService: false
    #kube-system-coredns-external-coredns
    serviceType: LoadBalancer
    # service:
    #   loadBalancerIP: 192.168.58.251
    servers:
      - zones:
        - zone: .
        port: 53
        plugins:
        - name: errors
        # Serves a /health endpoint on :8080, required for livenessProbe
        - name: health
          configBlock: |-
            lameduck 5s
        # Serves a /ready endpoint on :8181, required for readinessProbe
        - name: ready
        # Required to query kubernetes API for data
        # - name: kubernetes
        #   parameters: cluster.local in-addr.arpa ip6.arpa
        #   configBlock: |-
        #     pods insecure
        #     fallthrough in-addr.arpa ip6.arpa
        #     ttl 30
        # Serves a /metrics endpoint on :9153, required for serviceMonitor
        - name: prometheus
          parameters: 0.0.0.0:9153
        - name: etcd
           # see https://coredns.io/plugins/etcd/#syntax
          parameters: domain lan ${BASE_DOMAIN}
          configBlock: |-
            stubzones
            path /skydns
            endpoint http://dns-etcd-client:2379
        # - name: forward
        #   parameters: . /etc/resolv.conf
        - name: cache
          parameters: 30
        # - name: loop
        - name: reload
        - name: loadbalance
