---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: flux-system
spec:
  releaseName: hajimari
  chart:
    spec:
      chart: hajimari
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: hajimari
  install: {}
  interval: 10m0s
  targetNamespace: default
  values:
    env:
      TZ: Australia/Sydney
    # persistence:
    #   config:
    #     enabled: true
    #     mountPath: /config
    #     existingClaim: default-homeassistant-home-assistant-config
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - start.${BASE_DOMAIN}
            - start
            secretName: hajimari-tls
        hosts:
          - host: start.${BASE_DOMAIN}
            paths:
              - path: /
          - host: start
            paths:
              - path: /
    hajimari:
      # icons https://materialdesignicons.com/
      defaultEnable: false
      namespaceSelector:
        matchNames:
        - default
      # -- Override the title of the Hajimari pages
      title: Start page
      customApps:
      - name: Sonarr
        url: http://192.168.10.32:8989/
        icon: tv-box
      - name: Radarr
        url: http://192.168.10.123:7878/
        icon: filmstrip
      - name: Sabnzbd
        url: https://sabnzbd.borgs.net/
        icon: download-outline
      - name: Transmission
        url: http://192.168.10.20:9091/
        icon: briefcase-download
      - name: Emby
        url: https://emby.borgs.net
        icon: movie-play
      groups:
        - name: hajimari project (documention for this)
          links:
            - url: https://github.com/toboshii/hajimari/tree/main/charts/hajimari
              name: hajimari github
