---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.5.x
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  values:
    installCRDs: true
