---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    provider: webhook
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
    extraContainers:
      - name: unifi-webhook
        # renovate: datasource=github-releases depName=kashalls/external-dns-unifi-webhook
        image: ghcr.io/kashalls/external-dns-unifi-webhook:v0.3.0
        imagePullPolicy: IfNotPresent
        env:
          - name: UNIFI_HOST
            value: https://unifi.network.svc.cluster.local:8443
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-credentials
                key: username
          - name: UNIFI_PASS
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-credentials
                key: password
          - name: UNIFI_SKIP_TLS_VERIFY
            value: "true"
        ports:
          - name: http-webhook
            containerPort: 8888
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
