apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
    namespace: network-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:/vJDvtn5NBtO0YSd/z0ho4V7bBXYvx0ZeS9f8ZQItpQ=,iv:vzL8zjiAGO8FY4JewY7lXVD4x5b/8hFlrP779pZ++ms=,tag:AqKtOqbxTSs1wYvyFJurtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-07T00:16:02Z"
    mac: ENC[AES256_GCM,data:WIFOG7iLoUjs1kCI1wglpqfxOktEla9SEBWJYUrd8spv6+TQrYG8SWiXXFcfbfDtZ+rmJ8/72vrzhxQrUj2enoWerCz19vAUgXMABL3yLpDBKW2vV6EWAF0gB5fbrJfeK1gKbr/qMG4mKUjzMqnbXSB9mLVioYGaaPFMmAz+frw=,iv:YBQ+dFbDlR3WyA9vs9wMjVLrS0vWF82FkM3Tn9Pqy5c=,tag:FiEBJr7DvrutzUhLZ0ow2A==,type:str]
    pgp:
        - created_at: "2026-04-07T00:16:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/M6fje6Wa1jAQ/+KKzgVBmWqizdQ0FPsqkdb+2gzEQPeSkxnSSxZocCCN46
            NOk6EjYdncNJ8tUQm9UrnS3RCjCB0Ux1aKNntgZN1+ieI2NUanmczjA5gvJGEFEZ
            f2WrlZycTVqVHAGtN8XpzUqstS/BdL+DYKlEfqv2GFV/iCZB3Nx5HPln3x4kIwcB
            qBv+3tiWz5K09pvuiJjtzDkpcxRUamzANB4gRTQsJ9o/02jVZh464PavDchE6X2V
            eIq59dwMhEO6COwiv3rPUCRJpjtTPtU+A0wf1tvAlpvDebHceJUHl5weqtHK9ElV
            Kt8x5L5RDO8LvNOZejiJp15wRLZZwzZrCrl/LOsyunCrjvaiaB6gLkTMSUKDsIVV
            Q2c4iAO1HsIsOZvgxQv7JsSu4CVilXqU5lrbJLrb5eL5SCN+It53MsbssWqMZapU
            HERYCOk2oaYVOfw2hMe6qV1Eh9vCWW6rFdX/uTrb7JfOQPfQeUmefgbIrR5mlpbd
            IIZeo74j0R8M9nU7q9vqvSErgwSUOvpAp18f1/NS5pu5bf2KmlDV4qdfRlO33at7
            SIOiuBb+RUHn7E/niKWSbI9Dq6mT+MMy91BJQtpeBKmNMbN5cCXQ27M8sDetK2g5
            isqDOKngmiceuYvtS88z8G/kqLuN6YsE9ZSIhCPbFTwl1F/hkEGJvZ5YgKbAlUHU
            aAEHAhBzm11Y5g1wtwnaGcEJLH1CfqpaDwyvMvEqLBDDcdh4CtKk08x/zJ0AKnIF
            1V/1mAxRO3buRyR7wRsMNiFpJ01ECROOa5Uo5B+HWnk9pQL9dtttb2VxPP2z2OC4
            8BihVI+jW5vt
            =4fUi
            -----END PGP MESSAGE-----
          fp: E1B9ED7DD949E306B657E2EB001154C49571BA66
        - created_at: "2026-04-07T00:16:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/wevS2MWPqcAQ/+MSvhER4Hvwe6jODn8EefXEwZt4SdGbCl5zeQf0+NFnXx
            gRRdHaq6z+AopK4F7QBPL4Y4/jRyW1oI/ecijWsQ2BPM2UKLirn6nmiP9htpX7UX
            yVVoFY9xcbKx3pURVmJlyhK3Gj1tlvs++NuwOJdBbopVwKaQ4udxYpPrG9MrJYgJ
            cirZBoAXdBcMbq1Yl/VrjCkAq6AnpAOOGHH5GVbYUmFyjs9CyU2wQzLINXSTYpJ8
            OUwMuUp9C1bGGbrYHIhAKus+lGYceWwhcmon95BswzFhzFdZbFwgIefpJHVNCXbY
            nDnppNUZ6Zfp0tMC6fNzU6A5uEd8XMV0ikLnKwE5NIsJBckZ5+RgUFjoCizoGdxd
            PJEj+y8oBPlZ5CfdXPSadl3PC/4uWejwiLDbL23yhMgFV8ckntbwJl8ry4kS1llI
            kT+7WZwq74mFg+WuNZkS84pYocmal75qrIkjvA36O9Raydf2bkPfA2Wkj2NzY7f3
            LDLE4juTOg3YRX5vYJitH1v79QxKtOCs9YoHCPX/4ovUwyFS+CZPFxtw102Xtf6M
            bu0JD7qvMv8PvEcw/WeTUT5yWuuDoanS3PWHookd+fSgpshgrpN31UwbnMQrKYhn
            r4LSiuCmzmQXnmB346hc25x1i/4YMi4YSP4Y/eo/N5NyxXGWISgBtWOF7AD/bF/U
            aAEHAhCdZSRZ6R9dUXBF5jw+MBAlYst6bsq+kphXfJCulOb5uDOoYpHwZxO7ZM7p
            2NrOP5h3PhQZod43XhbzjeB4AvXnV8FTIv8cyka6CrG/wi6d2QiZ3zmcWzJ+v7fF
            udiNgknV/7iO
            =lpBx
            -----END PGP MESSAGE-----
          fp: DC28FBF0B880CCFC8CC1F5144447FB4C8CBA9DE0
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
