---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.7.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: ghcr.io/linuxserver/jackett
      tag: "0.22.2026"
      pullPolicy: IfNotPresent

    env:
      TZ: "Australia/Sydney"

    persistence:
      config:
        enabled: true
    # service:
    #   main:
    #     annotations:
    #       external-dns.alpha.kubernetes.io/hostname: jackettsvc.${BASE_DOMAIN}
    #     type: LoadBalancer
    #     externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        hosts:
          - host: jackett.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls.jackett
            hosts:
              - jackett.${BASE_DOMAIN}

    resources:
      requests:
        cpu: "0.02"
        memory: "256M"
      limits:
        memory: "512M"
