---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: ghcr.io/k8s-at-home/jackett
      tag: v0.18.1008
      pullPolicy: IfNotPresent

    env:
      TZ: "Australia/Sydney"

    persistence:
      config:
        enabled: true
        existingClaim: jackett-config

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        hosts:
          - host: jackett.${BASE_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: tls.jackett
            hosts:
              - jackett.${BASE_DOMAIN}

    resources:
      requests:
        cpu: "0.02"
        memory: "256M"
      limits:
        memory: "512M"