---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 4.x.x
  install: {}
  interval: 10m0s
  targetNamespace: default
  releaseName: mqtt
  values:
    env:
      TZ: Australia/Sydney
