---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tesla-proxy
  namespace: home-automation
# note values documented here https://artifacthub.io/packages/helm/bjw-s/common/0.2.2
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
    addons:
      codeserver:
        enabled: false
        image:
          repository: codercom/code-server
          tag: 4.90.3
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          tls:
            - hosts:
              - config.tesla-proxy.${BASE_DOMAIN}
              secretName: tesla-proxy-code-server-tls
          hosts:
            - host: config.tesla-proxy.${BASE_DOMAIN}
              paths:
                - path: /
        volumeMounts:
          - name: config
            mountPath: /config
    image:
      repository: iainbullock/tesla_http_proxy
      tag: "v1.0.5"
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    service:
      main:
        ports:
          http:
            port: 8099
            enabled: true
            primary: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - tesla-proxy.${BASE_DOMAIN}
            secretName: tesla-proxy-tls
        hosts:
          - host: tesla-proxy.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8099
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        mountPath: /data
      secret-config:
        enabled: true
        type: secret
        name: tesla-command-proxy
        mountPath: /data/config.sh
        readOnly: true
        subPath: config
