#!/usr/bin/env python3
"""Regenerate the EPG channel config for cluster/apps/media/epg from the YourTV API.

xmltv.net's region files are generated from YourTV, and key on the YourTV channel
id: `<channel id="<yourtv-id>auepg.com.au">`. This asks YourTV which channels the
region actually carries, and emits a sed map rewriting those ids to the canonical
`<id>.yourtv.au` form the EPG service publishes.

That indirection is the point: TVHeadend and MythTV are configured against
canonical ids, so swapping or adding a guide source later does not mean remapping
every channel by hand. Canonical ids are the numeric YourTV id rather than a slug
because slugs are not unique -- the Newcastle lineup has two channels called "7"
and two called "Sky News Regional".

    scripts/epg-gen-config.py                 # rewrite the ConfigMap in place
    scripts/epg-gen-config.py --region 94     # some other region (94 = Melbourne)

Re-run it after a lineup change and review the diff. YourTV has no endpoint that
lists regions; the ids are catalogued in the WebGrab+Plus siteini pack:
https://github.com/awiouy/webgrabplus/blob/master/config/siteini.pack/Australia/yourtv.com.au_regions.xml
"""

import argparse
import json
import pathlib
import sys
import urllib.error
import urllib.request

API = "https://www.yourtv.com.au/api"
# YourTV serves the API only to browser-ish clients.
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

DEFAULT_REGION = 184  # Newcastle
DEFAULT_OUT = "cluster/apps/media/epg/configmap-channels.yaml"
SOURCE_URL = "http://xmltv.net/xml_files/Newcastle.xml"


def fetch(path):
    req = urllib.request.Request(
        f"{API}/{path}", headers={"User-Agent": UA, "Accept": "application/json"}
    )
    try:
        resp = urllib.request.urlopen(req, timeout=60)
    except urllib.error.URLError as exc:
        raise SystemExit(f"{path}: {exc}") from None
    with resp:
        ctype = resp.headers.get("Content-Type", "")
        if "json" not in ctype:
            # An unknown region, or a reshuffled API, is served as an HTML error
            # page -- fail loudly rather than writing an empty map.
            raise SystemExit(f"{path}: expected JSON, got {ctype!r}")
        return json.load(resp)


def channels(region):
    raw = fetch(f"regions/{region}/channels")
    out = []
    for c in raw:
        cid = str(c["id"])
        # `description` is the long form ("NBN 9GEM NSW"); `name` is the short one.
        name = (c.get("description") or c.get("name") or cid).strip()
        out.append((cid, name))
    # Sorted for stable diffs -- the API's own order is lineup-ish but not guaranteed.
    return sorted(out, key=lambda t: (t[1].lower(), int(t[0])))


def channel_map(chans):
    lines = [
        "# Generated by scripts/epg-gen-config.py -- do not edit by hand.",
        "#",
        "# Rewrites the source's channel ids to canonical <yourtv-id>.yourtv.au ids,",
        "# so consumers are configured against ids that outlive a change of source.",
        "# One substitution covers both `id=` on <channel> and `channel=` on",
        "# <programme>. Channels the source carries but YourTV's region API does not",
        "# (radio, metro overflow) keep their original ids and are ignored downstream.",
        "#",
        "# Matches are anchored on the surrounding quotes: xmltv.net also carries ids",
        "# like `61-289721auepg.com.au`, which an unanchored match would partially",
        "# rewrite into a bogus canonical-looking id.",
    ]
    for cid, name in chans:
        lines.append(f's/"{cid}auepg\\.com\\.au"/"{cid}.yourtv.au"/g  # {name}')
    return "\n".join(lines) + "\n"


def indent(text, pad="    "):
    return "\n".join(pad + line if line else "" for line in text.split("\n"))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--region", type=int, default=DEFAULT_REGION)
    ap.add_argument("--source-url", default=SOURCE_URL)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    chans = channels(args.region)
    if not chans:
        print(f"no channels returned for region {args.region}", file=sys.stderr)
        return 1

    body = f"""---
# Generated by scripts/epg-gen-config.py -- do not edit by hand.
#   region:   {args.region} (YourTV region id)
#   channels: {len(chans)}
#   source:   {args.source_url}
apiVersion: v1
kind: ConfigMap
metadata:
  name: epg-channels
  namespace: media
data:
  channel-map.sed: |
{indent(channel_map(chans))}
"""
    pathlib.Path(args.out).write_text(body)
    print(f"wrote {args.out}: region {args.region}, {len(chans)} channels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
