# cluster/apps/home-automation/emhass/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emhass
    namespace: home-automation
stringData:
    secrets_emhass.yaml: ENC[AES256_GCM,data:KHIodc7vZRCH16fY5nFNHHi5tMCT/8iiy2OFyMiRumTSnn2Xv4KHsw//KYY2kzsB/+XMMSrdMWWZqw5hd4sX7Q1YZv42jzpfQZhL2kb7UUjhv4QRjQpbgwiJEaae74owXesGDvAC9LI6iXqJR3CLSOawnhS0kq48sCzt1mr389M5h9FwlG0G087qaZy5IAyNujX1bt45b8IR3dcSnUICtXhAjQl14SkSGngrX8DscyR73iIJZNKMrYGh7Q4RQN4pr9Vc5M3el5Ly9XaAmjuphFa9t1uyKYlHb+37WsXYn8bmyy2ifl6s3egxFhk3eLRjz4QTlp1Lf6mk4eb1GqvnCYh3JfcB/qYdOmHftGy+v7esuF14/oaAhh6Oac0M/QkxcMfqtTGQeuyBMwRtOXtq6GKwu6uy+SpyZ/NsCOJb4gE6Ka4=,iv:HwQVyU+opgtnp2h7zXXwjWjZmJ95ZCu/uNSI/rZAUQ0=,tag:GiISdcUsyj3Ab8YDP/Gvew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-22T23:39:09Z"
    mac: ENC[AES256_GCM,data:3RlIvWLc81v2cIRnln/x2ltQgeqPTV8eth0DFf5P7xn4ZCsML4A6mF4+slvoHopSD+8BX+ThJiqRFE3NXJx+nARzRTYjX7GiEclU8U/KjCRbhW/FNaxn5BYHdE6DfDrdRTOPtL9aeh4Quj9K5tnkog9Pg+Qrwwoc0UWYFlHBhGw=,iv:8tvRgoi6elG4LkWVDJbPObT+mRvhCTzmLoJJPBO9vFo=,tag:qhtcRkbzpihK+RoKafhUsg==,type:str]
    pgp:
        - created_at: "2026-04-22T23:39:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/M6fje6Wa1jARAAiBRTdpbwO13m1tWUvVuST3lanl5tVtd+NpY9zIZ8fpn6
            7W8e1EQN0jTOzgxd7morywHte6fz5xbUttC8BWrgazCy9L3qsSjY+PIhNRbA/lSD
            Hvql1HNbJ6O0qfX5k/+/YrqyddBEkkVwvbcS1cosmxKlsm/VP4oFyY4Hu0l0hX/x
            ZcWde+wDCjowZKb8skX37IsKnvHfwOoZhrdGOS59sQo2uGVMEgCmFiURxfVJ+pDI
            3F9IBzlM8/XeU/NUoGQhd9sIIVMzr9LEXp5O4rZKaGbooyXHyqkZ75n+kwhSL7NH
            M0vlzSexqdQvd+TwDQzGg/J+L93Zzzgn28kv8PUDXA403AuFOR0qXfCrurGciR6Q
            NBN+cbDVJ4FMwEzdzfITIjmcb/Y4KD+ep35YVjrf84mvhsEY5ApHitKM3FS9YUCW
            DwfIX7wEh20FC9j/ev6KOpvScraFjkLb5S5chchZBOPfOvxq9QFzEtK5iRnZsXfP
            A8cSWb6ENDWsu5rTQ1PVRCQwbFvarQzXzgZoEXgrcU4xbVN70T8FET3f9gRb+y3q
            G81v6yik+q+lxrblLtFFjwwDd/kM0e8ULmUo1I7cQjh51Zqaw3LGF9/64/8u5yW4
            +yccnYItDZ3bgr7dsYXk3kXCOqhdbDkRg8myvzW78Dxi9jl8udnJNHpCU8iPEBDU
            ZgEHAhCzPMBwxKfhnkmlUuG/CqftX2FTYDM7Eaw4CxseZmCHc/cYVZiSjrA3Poc4
            JQeEkik9iPQfdEopYPpt4u3V5kjB+R3otA8ZQAPSK6x8bUmX6zoClCkNO6C24ydV
            4LC9x3IRdQ==
            =xyrB
            -----END PGP MESSAGE-----
          fp: E1B9ED7DD949E306B657E2EB001154C49571BA66
        - created_at: "2026-04-22T23:39:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/wevS2MWPqcAQ//ajBbPgb73b7nKFnPk3m7gqJH4mEpdwjBDvVdC1m/EUIJ
            yLuoDZyiSWaSo1QMDUO0H+n7KOhofEObVbKOLaUtISDvwNkR4KnvkZo6k5VIa1wn
            Oz8+zn7tLhp8dfLVuc6GnmlspttBb+QC49OV9dGJITLhwI4zmxb0iDIWuceByUaw
            uBD2F3cCVl2WY7fZvlWPFiuJYbZCevi99lWzhDvlvBN0FJLPcakeo2eJ6Be2/Y8A
            mGP80WXVZmxHtvGGnqj2MH5xL5gDgeScmDpbPIRV2tdUvi/E9XBtZ2d0mKf2mYS0
            bm2EijOepmec4wf//+FXQR9+S9W8eOEW0IavXXE36hkHdkZzX97ZQVxoUxsqbuxz
            UegOnP8mT0MFn8Mt/0PJjTfqY4yzn5pX/tD16y4wosbjNSxbOT2Np9fTEBBTrG1a
            suCabz5Hly/FEMPD3HMQFf3ufVXRTGcRX7u9eiQFpxmgGz7M4+g9I477jJU8wA7B
            a62BaEQSk3bynLO5jg2KJ8r5OUbR8g/Fbl59rTpHu4273jFmp07jDdn88wu90dp0
            LMA/FtCngmeScq32BYatobozvvy++8KlZcUu7EOBE1QO0IAPECXDBhkuKU+V5D9M
            cC32+ORpiyk3xXzv7viF4GPzBofD4YWc/hCelWcCXbAW5DdT2jPbUoC6mAAmPGnU
            ZgEHAhDiKCKxsN6scdlWrxh72UP8eowFjekknYqY14JHEdWbEStfX5PU4X3e4yYi
            nzs4uefz5HNEsXYvw1aHAp2S4z6g2Bh7ydJgUNrBIFkfdxIZc/xVhJSsMPC4ZzS3
            DzyALnIOaA==
            =9Gnw
            -----END PGP MESSAGE-----
          fp: DC28FBF0B880CCFC8CC1F5144447FB4C8CBA9DE0
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
