---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flaresolverr
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: ghcr.io/thephaseless/byparr
      tag: "2.1.0"

    env:
      TZ: "Australia/Sydney"

    resources:
      requests:
        cpu: "0.02"
        memory: "256M"
      limits:
        memory: "512M"