---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idrac-r710
  namespace: network
spec:
  selector:
    matchLabels:
      app: idrac-r710
  template:
    metadata:
      labels:
        app: idrac-r710
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: idrac-r710
        image: domistyle/idrac6:v0.8
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        env:
          - name: IDRAC_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: idrac-passwords
          - name: IDRAC_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: idrac-passwords
          - name: IDRAC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: idrac-passwords
        readinessProbe:
          httpGet:
            path: /
            port: 5800
          tcpSocket:
            port: 5900
        livenessProbe:
          httpGet:
            path: /
            port: 5800
          tcpSocket:
            port: 5900
        ports:
        - containerPort: 5800
        - containerPort: 5900
---
apiVersion: v1
kind: Service
metadata:
  name: idrac-r710-web
  namespace: network
spec:
  selector:
    app: idrac-r710
  ports:
  - port: 5800
    targetPort: 5800
---
apiVersion: v1
kind: Service
metadata:
  name: idrac-r710-vnc
  namespace: network
spec:
  selector:
    app: idrac-r710
  ports:
  - port: 5900
    targetPort: 5900
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idrac-r710
  namespace: network
  labels:
    name: idrac-r710
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
    - secretName: "tls.idrac-r710"
      hosts:
        - "dellr710.${BASE_DOMAIN}"
  rules:
  - host: dellr710.${BASE_DOMAIN}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: idrac-r710-web
            port: 
              number: 5800
