---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tvheadend
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tvheadend
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 5.0.1 
  install: {}
  interval: 1m0s
  values:
    persistence:
      config:
        enabled: true
        annotations:
          volume.beta.kubernetes.io/storage-class: "freenas-iscsi-csi"
        size: 2Gi
        accessMode: ReadWriteOnce
      recordings:
        enabled: true
        size: 100Gi
        accessMode: ReadWriteMany
      timeshift:
        enabled: true
        size: 10.1Gi
        accessMode: ReadWriteMany
    service:
      main:
        ports:
          htsp:
            enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: tvh.${BASE_DOMAIN}
        type: LoadBalancer
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'TV Head end'
        tls:
          - hosts:
            - tvheadend.${BASE_DOMAIN}
            secretName: tvheadend-tls
        hosts:
          - host: tvheadend.${BASE_DOMAIN}
            paths:
              - path: /
    env:
      TZ: Australia/Sydney
    image:
      repository: ghcr.io/linuxserver/tvheadend
      tag: version-23754f9a

    # to access tv tuner
    nodeSelector:
      kubernetes.io/hostname: pi1

    securityContext:
      privileged: true

    #podAnnotations:
    #  k8s.v1.cni.cncf.io/networks: |
    #    [{
    #      "name":"macvlan-home-static",
    #      "namespace": "system",
    #      "ips": ["192.168.58.201/24"]
    #    }]

    resources:
      requests:
        cpu: "0.3"
        memory: "256Mi"
      limits:
        memory: "512Mi"
