---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
  install: {}
  interval: 10m0s
  targetNamespace: cert-manager
  values: {}
    # startupapicheck:
    #   backoffLimit: 10