---
- name: set path to cmdline.txt
  set_fact:
    cmdline_txt_path: /boot/cmdline.txt
- include_tasks: cmdline.yaml
  vars:
    key: cgroup_enable
    value: memory
    update: false
    # will add the argument if the key-value-pair doesn't exist
- include_tasks: cmdline.yaml
  vars:
    key: cgroup_enable
    value: cpu
    update: false
- include_tasks: cmdline.yaml
  vars:
    key: cgroup_memory
    value: 1
    update: true
    # will replace the value of the first matching key, if found;
    # will add it if it's not found
- name: Ensure 64bit mode
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^arm_64bit='
    line: arm_64bit=1
  register: arm64_enable
- name: Ensure 128mb gpu memory
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_mem='
    line: gpu_mem=128
  register: gpu_mem_128
- name: set reboot fact
  when: arm64_enable.changed or gpu_mem_128.changed
  set_fact:
    reboot_required: true
- name: reboot
  reboot:
  when: reboot_required is defined and reboot_required
- name: regather facts
  setup:
  when: reboot_required is defined and reboot_required
