---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-grafana
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
    image:
      repository: teslamate/grafana
      tag: "1.32.0"
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    podSecurityContext:
      fsGroup: 472
    env:
      DATABASE_USER: teslamate
      DATABASE_PASS:
       valueFrom:
          secretKeyRef:
            name: teslamate
            key: password
      DATABASE_NAME: teslamate
      DATABASE_HOST: teslamate-db
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        # type: pvc
        # accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /var/lib/grafana
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - teslamate-grafana.${BASE_DOMAIN}
            secretName: teslamate-grafana-tls
        hosts:
          - host: teslamate-grafana.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
