# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - secrets.yaml
    - postgresql.yaml
    - grafana-helmrelease.yaml
    - teslamate-helmrelease.yaml
    - abrp-helmrelease.yaml
    