---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-db
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
    image:
      repository: postgresql
      tag: 14.7-alpine
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      POSTGRES_USER: teslamate
      POSTGRES_DB: teslamate
      POSTGRES_PASSWORD:
       valueFrom:
          secretKeyRef:
            name: teslamate
            key: POSTGRES_DATABASE_PASS
    service:
      main:
        ports:
          postgres:
            port: 5432
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        # type: pvc
        # accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /var/lib/postgresql/data
