---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-db
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      # 16.2.1 is the last version before oct:// ? need to update flux?
      version: 16.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nameOverride: teslamate-db
    image:
      repository: bitnami/postgresql
      tag: 17.5.0-debian-12-r20
    auth:
      username: teslamate
      existingSecret: teslamate
      database: teslamate
    primary:
      nodeSelector:
        storage: longhorn
      persistence:
        storageClass: longhorn
        size: 5Gi
