---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-db
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 12.8.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nameOverride: teslamate-db
    image:
      repository: bitnami/postgresql
      tag: 14.7.0
    auth:
      username: teslamate
      existingSecret: teslamate
      database: teslamate
    primary:
      nodeSelector:
        storage: longhorn
      persistence:
        storageClass: longhorn
        size: 2Gi