---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-nas-nfs
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  install: {}
  interval: 10m0s
  targetNamespace: kube-system
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    driver:
      config:
        driver: freenas-nfs
        httpConnection:
          allowInsecure: true
          port: 443
          protocol: https
          username: root
        instance_id: null
        nfs:
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMapallGroup: ""
          shareMapallUser: ""
          shareMaprootGroup: wheel
          shareMaprootUser: root
        sshConnection:
          port: 22
          username: csi
        zfs:
          cli:
            paths:
              chroot: /usr/sbin/chroot
              sudo: /usr/local/bin/sudo
              zfs: /sbin/zfs
              zpool: /sbin/zpool
            sudoEnabled: true
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetParentName: tank/k8s/nfs
          datasetPermissionsGroup: wheel
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: root
          datasetProperties:
            org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace]
}}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
          detachedSnapshotsDatasetParentName: tank/k8s/nfs-snaps
    storageClasses:
      - allowVolumeExpansion: true
        defaultClass: true
        mountOptions:
        - noatime
        - nfsvers=3
        name: freenas-nfs-csi
        parameters:
          fsType: nfs
        reclaimPolicy: Delete
        secrets:
          controller-expand-secret: null
          controller-publish-secret: null
          node-publish-secret: null
          node-stage-secret: null
          provisioner-secret: null
        volumeBindingMode: Immediate
    volumeSnapshotClasses:
      - name: freenas-nfs-csi
        # annotations: {}
        # labels: {}
        deletionPolicy: Delete
        # parameters:
        # secrets:
        #   snapshotter-secret:
  valuesFrom:
  - kind: Secret
    name: freenas-password
    targetPath: driver.config.httpConnection.host
    valuesKey: host
  - kind: Secret
    name: freenas-password
    targetPath: driver.config.httpConnection.password
    valuesKey: password
  - kind: Secret
    name: freenas-password
    targetPath: driver.config.nfs.shareHost
    valuesKey: host
  - kind: Secret
    name: freenas-password
    targetPath: driver.config.sshConnection.host
    valuesKey: host
  - kind: Secret
    name: freenas-password
    targetPath: driver.config.sshConnection.password
    valuesKey: password
    