---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 8.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: "0.13.2"
    nodeSelector:
      kubernetes.io/arch: amd64
      storage: longhorn
      feature.node.kubernetes.io/usb-fe_1a6e_089a.present: 'true'
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 512m
        memory: 512Mi
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Frigate'
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          # hajimari.io/url
        tls:
          - hosts:
            - frigate.${BASE_DOMAIN}
            secretName: frigate-tls
        hosts:
          - host: frigate.${BASE_DOMAIN}
            paths:
              - path: /
    service:
      main:
        ports:
          rtmp:
            enabled: true
    env:
      TZ: Australia/Sydney
    envFrom:
      - secretRef:
          name: frigate-secrets
    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate-config"
    persistence:
      data:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
      media:
        enabled: true
        mountPath: /media/frigate
        size: 150Gi
        accessMode: ReadWriteMany
        # existingClaim: frigate-media
      # video10:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video10
      # video11:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video11
      # video12:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video12
      # video13:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video13
      # video14:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video14
      # video15:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video15
      # video16:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video16
    securityContext:
      privileged: true
      # capabilities:
      #   add:
      #     - CAP_SYS_ADMIN
    podSecurityContext:
      supplementalGroups:
        - 44
    configmap:
      config:
        enabled: false