---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.8.4-aarch64
    nodeSelector:
      kubernetes.io/arch: arm64
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Frigate'
          # hajimari.io/url
        tls:
          - hosts:
            - frigate.${BASE_DOMAIN}
            secretName: frigate-tls
        hosts:
          - host: frigate.${BASE_DOMAIN}
            paths:
              - path: /
    service:
      main:
        ports:
          rtmp:
            enabled: true
    env:
      TZ: Australia/Sydney
    envFrom:
      - secretRef:
          name: frigate-secrets
    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate-config"
    persistence:
      media:
        enabled: true
        mountPath: /media/frigate
        size: 100Gi
        accessMode: ReadWriteMany
        # existingClaim: frigate-media
      # video10:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video10
      # video11:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video11
      # video12:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video12
      # video13:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video13
      # video14:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video14
      # video15:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video15
      # video16:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video16
    securityContext:
      privileged: true
      # capabilities:
      #   add:
      #     - CAP_SYS_ADMIN
    podSecurityContext:
      supplementalGroups:
        - 44
    config: |
      mqtt:
        host: mqtt-mosquitto
        topic_prefix: frigate
      detectors:
        cpu1:
          type: cpu
        cpu2:
          type: cpu
      cameras:
        # front:
        #   motion:
        #     mask:
        #       - 2013,1480,2625,1485,2619,1434,2008,1433
        #       - 283,936,461,958,626,658,718,926,970,892,1094,678,1092,454,903,363,741,406,663,113,296,157,197,0,0,0          
        #   zones:
        #     road:
        #       coordinates: 837,316,1623,165,2688,163,2688,0,0,0,0,544
        #     front_yard:
        #       coordinates: 2688,1520,0,1520,0,536,929,296,1619,168,2688,703
        #   ffmpeg:
        #     inputs:
        #       - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/2
        #         roles:
        #           - detect
        #           - rtmp
        #           - clips
        #           - record
        #   width: 2688
        #   height: 1520
        #   fps: 5
        #   clips:
        #     enabled: true
        #   snapshots:
        #     enabled: true
        front:
          motion:
            mask:
              - 472,360,640,360,640,329,475,331
              - 139,180,162,225,227,219,243,198,265,157,258,119,218,86,151,109
              - 0,232,117,212,148,132,172,49,131,48,68,67,44,0,0,0
          zones:
            road:
              coordinates: 0,132,0,0,640,0,640,31,346,39
            front_yard:
              coordinates: 0,360,522,360,640,165,382,30,0,115              
          ffmpeg:
            inputs:
              - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.58.113/Streaming/Channels/1
                roles:
                  - clips
                  - record
                  # - detect
                  # - rtmp
            # hwaccel_args:
            #   - -c:v
            #   - h264_v4l2m2m
          width: 640
          height: 360
          fps: 5
          clips:
            enabled: true
          snapshots:
            enabled: true
        garage:
          motion:
            mask:
              - 408,48,409,21,26,21,27,49
          zones:
            all:
              coordinates: 0,480,640,480,640,0,0,0
          ffmpeg:
            inputs:
              - path: http://192.168.58.114:8181/videostream.cgi?user=admin&pwd={FRIGATE_CAMERA2_PASSWORD}
                roles:
                  - clips
                  - record
                  - detect
                  - rtmp
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -r
              - "20" # <---- adjust depending on your desired frame rate from the mjpeg image
              - -use_wallclock_as_timestamps
              - "1"
            output_args:
              record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vf format=yuv420p -c:v h264_v4l2m2m -an
              clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vf format=yuv420p -c:v h264_v4l2m2m -an
              rtmp: -vf format=yuv420p -c:v h264_v4l2m2m -an -f flv
          width: 640
          height: 480
          fps: 5
          clips:
            enabled: true
          snapshots:
            enabled: true
      clips:
        retain:
          default: 30
          objects:
            car: 2
      snapshots:
        retain:
          default: 30
          objects:
            car: 2
      record:
        enabled: true
        retain_days: 1
      objects:
        track:
          - person
          - cat
          - car
          - bicycle
          - motorcycle
        filters:
          person:
            min_score: 0.4
            threshold: 0.5
          cat:
            min_score: 0.4
            threshold: 0.5
          car:
            min_score: 0.4
            threshold: 0.5
          bicycle:
            min_score: 0.4
            threshold: 0.5
          motorcycle:
            min_score: 0.4
            threshold: 0.5
      motion:
        # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
        # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
        # The value should be between 1 and 255.
        threshold: 35
        # Optional: Minimum size in pixels in the resized motion image that counts as motion
        # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
        # moving objects. DEFAULT 100
        contour_area: 35
        # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
        # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
        # Too low and a fast moving person wont be detected as motion.
        # delta_alpha: 0.2
        # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
        # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
        # Low values will cause things like moving shadows to be detected as motion for longer.
        # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
        # frame_alpha: 0.2
        # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height)
        # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
        # Lower values result in less CPU, but small changes may not register as motion.
        # frame_height: 180
      logger:
        # Optional: default log level (default: shown below) (info)
        default: info
