---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 8.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install: {}
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: "0.16.4"
    nodeSelector:
      kubernetes.io/arch: amd64
      storage: longhorn
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/usb-ff_18d1_9302.present
              operator: In
              values:
              - 'true'
          - matchExpressions:
            - key: feature.node.kubernetes.io/usb-fe_1a6e_089a.present
              operator: In
              values:
              - 'true'
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 512m
        memory: 1Gi
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'home-automation'
          hajimari.io/appName: 'Frigate'
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          # hajimari.io/url
        tls:
          - hosts:
            - frigate.${BASE_DOMAIN}
            secretName: frigate-tls
        hosts:
          - host: frigate.${BASE_DOMAIN}
            paths:
              - path: /
      go2rtc:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
        tls:
          - hosts:
            - go2rtc.frigate.${BASE_DOMAIN}
            secretName: go2rtc-frigate-tls
        hosts:
          - host: go2rtc.frigate.${BASE_DOMAIN}
            paths:
              - path: /
                service:
                  name: frigate
                  port: 1984
    service:
      main:
        ports:
          rtmp:
            enabled: true
          go2rtc:
            enabled: true
            port: 1984
      webrtc:
        enabled: true
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: webrtc.frigate.${BASE_DOMAIN}
        externalTrafficPolicy: Local
        ports:
          rtmp-tcp:
            enabled: true
            port: 8555
            protocol: TCP
          rtmp-udp:
            enabled: true
            port: 8555
            protocol: UDP
    env:
      TZ: Australia/Sydney
    envFrom:
      - secretRef:
          name: frigate-secrets
    probes:
        liveness:
          custom: true
          spec:
            httpGet:
              port: 5000
              path: /api/
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
        readiness:
          custom: true
          spec:
            httpGet:
              port: 5000
              path: /api/
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
        # startup:
        #   custom: true
        #   spec:
        #     tcpSocket:
        #       port: 5000
        #     initialDelaySeconds: 0
        #     failureThreshold: 30
        #     timeoutSeconds: 1
        #     periodSeconds: 5
    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate-config"
    persistence:
      data:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
      media:
        enabled: true
        mountPath: /media/frigate
        size: 150Gi
        accessMode: ReadWriteMany
        # existingClaim: frigate-media
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/usb
      # video11:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video11
      # video12:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video12
      # video13:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video13
      # video14:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video14
      # video15:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video15
      # video16:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/video16
    securityContext:
      privileged: true
      # capabilities:
      #   add:
      #     - CAP_SYS_ADMIN
    podSecurityContext:
      supplementalGroups:
        - 44
    configmap:
      config:
        enabled: false