apiVersion: v1
stringData:
    FRIGATE_CAMERA_PASSWORD: ENC[AES256_GCM,data:Grdvbuvl7PP9,iv:3xymqgB/5bnhqEmRLxplJE9vFnjFuWR4iCNZUAz+iy0=,tag:E+9/whD5RtZaRebPiGwIUw==,type:str]
    FRIGATE_CAMERA2_PASSWORD: ENC[AES256_GCM,data:NIodH8+eqg==,iv:HcW0zvIeiBYBlWxu5DEINW3cAaRVNeRAmah4+aA4KHk=,tag:fuQ+UZ/8VC2wpduRU3xG8Q==,type:str]
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home-automation
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-11T04:15:35Z"
    mac: ENC[AES256_GCM,data:vskfOX/8+6vNwovXjf/rluhoBVIoq/LkLP3bh9dXK+Tkh/knI4zLLZuzzQX9jJ+xaY75cWRVl8nfEm1+KaIh2VPse2DwsvvrAV3RTvtVo+FUmPtV3sZe5jztrQa/lq53qMq+7IJbIO7X7m3nJYGIrfiM9/FMPmrqTchvRF7ZhzM=,iv:YcUmJnxguy9owWGVPaFr8VLdPICaRyw318wjHeeYcxM=,tag:kWa9Zt7lOUEtf48786+Bbg==,type:str]
    pgp:
        - created_at: "2021-09-03T04:11:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/M6fje6Wa1jAQ//eKw4IwRKyCajFZQakQPFitdovFr2FN63E0D+4q2ny67s
            84Qdm3fYqQ7S8f2zvvkoR4kXjujCNOvIaeRcwJBp3bG0adnX5ZhEoTX/QYFJGPdQ
            Hm8kFsdC6B1mo8bNDvJRZAEhtIQ+rpey3zJ1Zluxt9QXiTsUJy6xZbO6IOtlKvwB
            5ZMnx6C1/5jpkrcF16akiv5SDuetSgVAwbKXQFCfeAY+1TvUxn47WiFlnRgK1t+G
            A2OOKUlWYvwodT0mN+dGWG4zEgXWHlUvIUjmM7BvoYsxxcJK1rvqiw6HL5f/q+Cd
            gxAk48v0PUr2EEx5b6Fo+NSdZtm3khGZLybriQngbBFwRYgs8wsb3dxY6Mxn9CGh
            qnO5ITfwQpxralxrpNwhElnQ3RVFYqXnyNUPdmGkw94YdghyYSCoDqnahCgyHkyz
            F/4mj2+Ptx4GQD9xvopwW3CUYqocpSUtd8zdyjBq7hfErj2QihbWWBB9+2Vnh8AN
            JImuC8ZjGvN8YBvCBNrTGN1f7h3OmL44rCOLC+AgtzI6aruV+gnc3cTEUwDUZC6N
            CNulRjOqyQEd3Ztzhnrkz19mkfr1RwxftRtgfkv+GQiWhpvrR1XVjh4RE41PzPWR
            p6xFOBv3JCuk7q8nGPvwUwyxIH5mz1bwYHYdyxe5KJRfmRpSJmia11dobDlOOcHU
            aAEHAhVry9XAxuLkU6G0BOFqEK6dmOgMjDIt+ExTE9MRF953X3lznY3qEPNGYyyj
            e3LxiAolhVPBVXflSCuOfg+iqyCGINeEM+TwkLI1jm2nco0tp9R7Q1slG55UC8X+
            bHSl6/iAd6lF
            =zNEj
            -----END PGP MESSAGE-----
          fp: E1B9ED7DD949E306B657E2EB001154C49571BA66
        - created_at: "2021-09-03T04:11:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/wevS2MWPqcAQ//Y0N6GzKCllcXxUbWiMXyxgx6S77GRi6tiz2tsyL20TRt
            8LcGuK/tn4m6rDa0PU5UOYMgDXMPMSy/u8xc+gjydhhj93R1Ai/s135cuvTK69cn
            QFi9oHGwg1PxPEiz/5fyzmk/O0ErKxAp9uNLqUVPHbWNCZ5ESENTQGaOGpFuj34K
            fazZ0e9acB1AgNHI/IYZEoTqQ/VCNdDSw2CvpV3PsKMuXEhESuGA0tEADyLuNCRt
            9uCZgSchvNEL92hK2US588gk19ok1nwLFdEFiyUOsncfyHqPn45+uYTBvl63jEi0
            /Xe9Met8Hjj+STOfxlwZrz0FI1b4wlTnX2cLsyTscZmKu+D5r57+9xnL96zsz3C+
            +uHtRiuyH8vqFCdlvF2QnyhhxpbsXLqhD6fIEvz1H45Vklq2gbcd3d4y6+xny5fR
            mx1mzFWcx11wdBkac011kMLRcr8H/c4y9JGWFGp0Rwln1FcajPyfycjqXupEPkD5
            bCmoAEbFPOlE7FCUqhkpjETleJYYnQefqdHUYvpm8Nps8lmKOPIXiBaeFlay85WI
            C3x4WDQb8T2xRwWCqXKWTYOfmHnsoxrDdhNvO609WPy9jMSmjKYF2xyjdGNjUm6+
            3ZItq0JsFtBDmbNdvDlflzbsHyJ3SuhcCSoeI+C+beimYyDgf8T07ToJwEAsyp7U
            aAEHAhUpvZfdqBLltWoG0oy6YFCLq2yXoK0kS5ESIUvQaH3cFyHIiIPmeN820cT+
            I9sJutHDUSL9+0aCUbUeG0jxjb8JsK5HGysJxw8QNJxcdfMW+wqLx9rP8oIsuMm1
            JqMJ2wPwjt8L
            =8LaS
            -----END PGP MESSAGE-----
          fp: DC28FBF0B880CCFC8CC1F5144447FB4C8CBA9DE0
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
