---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uisp
  namespace: network
# note values documented here https://artifacthub.io/packages/helm/bjw-s/common/0.2.2
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
      kubernetes.io/hostname: pve
    image:
      repository: nico640/docker-unms
      tag: "2.4.206"
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: "Australia/Sydney"
    service:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: uisp-external.${BASE_DOMAIN}
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 80
            enabled: true
          https:
            port: 443
            enabled: true
            primary: true
          netflow:
            port: 2055
            protocol: UDP
            enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          traefik.ingress.kubernetes.io/router.middlewares: network-system-https-redirectscheme@kubernetescrd
          traefik.ingress.kubernetes.io/service.serversscheme: https
        tls:
          - hosts:
            - uisp.${BASE_DOMAIN}
            secretName: uisp-tls
        hosts:
          - host: uisp.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 443
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        mountPath: /config
