---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: signtools
  namespace: home-automation
# note values documented here https://artifacthub.io/packages/helm/bjw-s/common/0.2.2
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 5m
  interval: 10m0s
  values:
    nodeSelector:
      storage: longhorn
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.92.2
        workingDir: "/data"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/data/.vscode"
          - --extensions-dir
          - "/data/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          tls:
            - hosts:
              - config.signtools.${BASE_DOMAIN}
              secretName: signtools-code-server-tls
          hosts:
            - host: config.signtools.${BASE_DOMAIN}
              paths:
                - path: /
        volumeMounts:
          - name: data
            mountPath: /data
    image:
      repository: signtools/signtools
      tag: "3.0.4"
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    args:
      - -config
      - /data/signer-cfg.yml
    env:
      TZ: "Australia/Sydney"
    service:
      main:
        ports:
          http:
            port: 8080
            enabled: true
            primary: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
          - hosts:
            - signtools.${BASE_DOMAIN}
            secretName: signtools-tls
        hosts:
          - host: signtools.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
    persistence:
      signtools-config:
        enabled: true
        type: secret
        name: signtools-config
        mountPath: /signer-cfg.yml
        readOnly: false
        subPath: signer-cfg.yml
      config:
        enabled: false
      data:
        type: pvc
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 5Gi
        mountPath: /data
      
