---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smtp
  namespace: network
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://bokysan.github.io/docker-postfix/
      chart: mail
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: docker-postfix
        namespace: flux-system
      interval: 10m0s
  install: {}
  values:
    pod:
      annotations:
        configmap.reloader.stakater.com/reload: "smtp-mail"
    config:
      general:
        # RELAYHOST: ${SMTP_HOST}
        # RELAYHOST_USERNAME: ${SMTP_USER}
        MASQUERADED_DOMAINS: ${EXTERNAL_DOMAIN}
        ALLOW_EMPTY_SENDER_DOMAINS: 'true'
        LOG_FORMAT: json
      postfix:
        hostname: smtp-internal.${EXTERNAL_DOMAIN}
    # secret:
    #   RELAYHOST_PASSWORD: ${SMTP_PASS}
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: smtp.${BASE_DOMAIN}
