---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smtp
  namespace: network
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://bokysan.github.io/docker-postfix/
      chart: mail
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: docker-postfix
        namespace: flux-system
      interval: 10m0s
  install: {}
  values:
    pod:
      annotations:
        configmap.reloader.stakater.com/reload: "smtp-mail"
    config:
      general:
        # RELAYHOST: ${SMTP_HOST}
        # RELAYHOST_USERNAME: ${SMTP_USER}
        DKIM_SELECTOR: ${DKIM_KEY_NAME}
        MASQUERADED_DOMAINS: ${EXTERNAL_DOMAIN}
        ALLOWED_SENDER_DOMAINS: ${EXTERNAL_DOMAIN}
        ALLOW_EMPTY_SENDER_DOMAINS: 'true'
        # LOG_FORMAT: json
        # INBOUND_DEBUGGING: '1'
      postfix:
        hostname: smtp-internal.${EXTERNAL_DOMAIN}
    # secret:
    #   RELAYHOST_PASSWORD: ${SMTP_PASS}
    persistence:
      storageClass: longhorn
    nodeSelector:
      storage: longhorn
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: smtp.${BASE_DOMAIN}
    # mountSecret:
    #   enabled: true
    #   path: /etc/opendkim/keys
    #   data:
    #     borgs.net.private: ${DKIM_PRIVATE_KEY}
    extraVolumes:
      - name: mount-dkim
        secret:
          secretName: smtp-dkim-keys
    extraVolumeMounts:
      - name: mount-dkim
        mountPath: /etc/opendkim/keys
        readOnly: true
